package com.lujun61.beans.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class DetailOrderItem {

    private String status;
    private String receiverMobile;
    private String receiverAddress;
    private String receiverName;
    private Integer payType;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.item_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productImg;


    private String skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.sku_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_price
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.buy_counts
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer buyCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.total_amount
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.basket_date
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String basketDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.buy_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String buyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.is_comment
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer isComment;
}