package com.lujun61.beans.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class DetailOrders {

    private List<OrderItem> orderItems;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.untitled
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String untitled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver_mobile
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver_address
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total_amount
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.actual_amount
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer actualAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_type
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_remark
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String orderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delivery_type
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String deliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delivery_flow_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String deliveryFlowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_freight
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private BigDecimal orderFreight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delete_status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer deleteStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delivery_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.flish_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date flishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cancel_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date cancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.close_type
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer closeType;

}