package com.lujun61.beans.entity;

import java.util.Date;

public class IndexImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.img_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.img_url
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.img_bg_color
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String imgBgColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.prod_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.index_type
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer indexType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.seq
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.img_id
     *
     * @return the value of index_img.img_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.img_id
     *
     * @param imgId the value for index_img.img_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setImgId(String imgId) {
        this.imgId = imgId == null ? null : imgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.img_url
     *
     * @return the value of index_img.img_url
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.img_url
     *
     * @param imgUrl the value for index_img.img_url
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.img_bg_color
     *
     * @return the value of index_img.img_bg_color
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getImgBgColor() {
        return imgBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.img_bg_color
     *
     * @param imgBgColor the value for index_img.img_bg_color
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setImgBgColor(String imgBgColor) {
        this.imgBgColor = imgBgColor == null ? null : imgBgColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.prod_id
     *
     * @return the value of index_img.prod_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.prod_id
     *
     * @param prodId the value for index_img.prod_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.category_id
     *
     * @return the value of index_img.category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.category_id
     *
     * @param categoryId the value for index_img.category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.index_type
     *
     * @return the value of index_img.index_type
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getIndexType() {
        return indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.index_type
     *
     * @param indexType the value for index_img.index_type
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setIndexType(Integer indexType) {
        this.indexType = indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.seq
     *
     * @return the value of index_img.seq
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.seq
     *
     * @param seq the value for index_img.seq
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.status
     *
     * @return the value of index_img.status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.status
     *
     * @param status the value for index_img.status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.create_time
     *
     * @return the value of index_img.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.create_time
     *
     * @param createTime the value for index_img.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.update_time
     *
     * @return the value of index_img.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.update_time
     *
     * @param updateTime the value for index_img.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}