package com.lujun61.beans.entity;

import java.util.List;

public class MultiCategory {

    // 存储首页多级商品推荐下Top6的商品信息  【专注于商品信息】
    private List<ProductDetail> products;

    // 首页多级类别   【专注于类别信息】
    private List<Category> categories;

    public List<Category> getCategories() {
        return categories;
    }

    public List<ProductDetail> getProducts() {
        return products;
    }

    public void setProducts(List<ProductDetail> products) {
        this.products = products;
    }

    public void setCategories(List<Category> categories) {
        this.categories = categories;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_level
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer categoryLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.parent_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_icon
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String categoryIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_slogan
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String categorySlogan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_pic
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String categoryPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_bg_color
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String categoryBgColor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param categoryId the value for category.category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_level
     *
     * @return the value of category.category_level
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getCategoryLevel() {
        return categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_level
     *
     * @param categoryLevel the value for category.category_level
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCategoryLevel(Integer categoryLevel) {
        this.categoryLevel = categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.parent_id
     *
     * @return the value of category.parent_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.parent_id
     *
     * @param parentId the value for category.parent_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_icon
     *
     * @return the value of category.category_icon
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getCategoryIcon() {
        return categoryIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_icon
     *
     * @param categoryIcon the value for category.category_icon
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCategoryIcon(String categoryIcon) {
        this.categoryIcon = categoryIcon == null ? null : categoryIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_slogan
     *
     * @return the value of category.category_slogan
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getCategorySlogan() {
        return categorySlogan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_slogan
     *
     * @param categorySlogan the value for category.category_slogan
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCategorySlogan(String categorySlogan) {
        this.categorySlogan = categorySlogan == null ? null : categorySlogan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_pic
     *
     * @return the value of category.category_pic
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getCategoryPic() {
        return categoryPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_pic
     *
     * @param categoryPic the value for category.category_pic
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCategoryPic(String categoryPic) {
        this.categoryPic = categoryPic == null ? null : categoryPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_bg_color
     *
     * @return the value of category.category_bg_color
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getCategoryBgColor() {
        return categoryBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_bg_color
     *
     * @param categoryBgColor the value for category.category_bg_color
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCategoryBgColor(String categoryBgColor) {
        this.categoryBgColor = categoryBgColor == null ? null : categoryBgColor.trim();
    }
}