package com.lujun61.beans.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.item_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.sku_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.sku_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_price
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.buy_counts
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer buyCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.total_amount
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.basket_date
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date basketDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.buy_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date buyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.is_comment
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer isComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.item_id
     *
     * @return the value of order_item.item_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.item_id
     *
     * @param itemId the value for order_item.item_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.order_id
     *
     * @return the value of order_item.order_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.order_id
     *
     * @param orderId the value for order_item.order_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_id
     *
     * @return the value of order_item.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_id
     *
     * @param productId the value for order_item.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_name
     *
     * @return the value of order_item.product_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_name
     *
     * @param productName the value for order_item.product_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_img
     *
     * @return the value of order_item.product_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_img
     *
     * @param productImg the value for order_item.product_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg == null ? null : productImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sku_id
     *
     * @return the value of order_item.sku_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sku_id
     *
     * @param skuId the value for order_item.sku_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sku_name
     *
     * @return the value of order_item.sku_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sku_name
     *
     * @param skuName the value for order_item.sku_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_price
     *
     * @return the value of order_item.product_price
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_price
     *
     * @param productPrice the value for order_item.product_price
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.buy_counts
     *
     * @return the value of order_item.buy_counts
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getBuyCounts() {
        return buyCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.buy_counts
     *
     * @param buyCounts the value for order_item.buy_counts
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setBuyCounts(Integer buyCounts) {
        this.buyCounts = buyCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.total_amount
     *
     * @return the value of order_item.total_amount
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.total_amount
     *
     * @param totalAmount the value for order_item.total_amount
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.basket_date
     *
     * @return the value of order_item.basket_date
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getBasketDate() {
        return basketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.basket_date
     *
     * @param basketDate the value for order_item.basket_date
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setBasketDate(Date basketDate) {
        this.basketDate = basketDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.buy_time
     *
     * @return the value of order_item.buy_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.buy_time
     *
     * @param buyTime the value for order_item.buy_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.is_comment
     *
     * @return the value of order_item.is_comment
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.is_comment
     *
     * @param isComment the value for order_item.is_comment
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setIsComment(Integer isComment) {
        this.isComment = isComment;
    }
}