package com.lujun61.beans.entity;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.root_category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer rootCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sold_num
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer soldNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.content
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.root_category_id
     *
     * @return the value of product.root_category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getRootCategoryId() {
        return rootCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.root_category_id
     *
     * @param rootCategoryId the value for product.root_category_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setRootCategoryId(Integer rootCategoryId) {
        this.rootCategoryId = rootCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sold_num
     *
     * @return the value of product.sold_num
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getSoldNum() {
        return soldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sold_num
     *
     * @param soldNum the value for product.sold_num
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setSoldNum(Integer soldNum) {
        this.soldNum = soldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_status
     *
     * @return the value of product.product_status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_status
     *
     * @param productStatus the value for product.product_status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProductStatus(Integer productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.content
     *
     * @return the value of product.content
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.content
     *
     * @param content the value for product.content
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}