package com.lujun61.beans.entity;

import java.util.Date;

public class ProductParams {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.param_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String paramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.product_place
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String productPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.foot_period
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String footPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.brand
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.factory_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String factoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.factory_address
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String factoryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.packaging_method
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String packagingMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.weight
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.storage_method
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String storageMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.eat_method
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String eatMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_params.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.param_id
     *
     * @return the value of product_params.param_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.param_id
     *
     * @param paramId the value for product_params.param_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setParamId(String paramId) {
        this.paramId = paramId == null ? null : paramId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.product_id
     *
     * @return the value of product_params.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.product_id
     *
     * @param productId the value for product_params.product_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.product_place
     *
     * @return the value of product_params.product_place
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getProductPlace() {
        return productPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.product_place
     *
     * @param productPlace the value for product_params.product_place
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProductPlace(String productPlace) {
        this.productPlace = productPlace == null ? null : productPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.foot_period
     *
     * @return the value of product_params.foot_period
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getFootPeriod() {
        return footPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.foot_period
     *
     * @param footPeriod the value for product_params.foot_period
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setFootPeriod(String footPeriod) {
        this.footPeriod = footPeriod == null ? null : footPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.brand
     *
     * @return the value of product_params.brand
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.brand
     *
     * @param brand the value for product_params.brand
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.factory_name
     *
     * @return the value of product_params.factory_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.factory_name
     *
     * @param factoryName the value for product_params.factory_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.factory_address
     *
     * @return the value of product_params.factory_address
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getFactoryAddress() {
        return factoryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.factory_address
     *
     * @param factoryAddress the value for product_params.factory_address
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setFactoryAddress(String factoryAddress) {
        this.factoryAddress = factoryAddress == null ? null : factoryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.packaging_method
     *
     * @return the value of product_params.packaging_method
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getPackagingMethod() {
        return packagingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.packaging_method
     *
     * @param packagingMethod the value for product_params.packaging_method
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setPackagingMethod(String packagingMethod) {
        this.packagingMethod = packagingMethod == null ? null : packagingMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.weight
     *
     * @return the value of product_params.weight
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.weight
     *
     * @param weight the value for product_params.weight
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.storage_method
     *
     * @return the value of product_params.storage_method
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getStorageMethod() {
        return storageMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.storage_method
     *
     * @param storageMethod the value for product_params.storage_method
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setStorageMethod(String storageMethod) {
        this.storageMethod = storageMethod == null ? null : storageMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.eat_method
     *
     * @return the value of product_params.eat_method
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getEatMethod() {
        return eatMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.eat_method
     *
     * @param eatMethod the value for product_params.eat_method
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setEatMethod(String eatMethod) {
        this.eatMethod = eatMethod == null ? null : eatMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.create_time
     *
     * @return the value of product_params.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.create_time
     *
     * @param createTime the value for product_params.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_params.update_time
     *
     * @return the value of product_params.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_params.update_time
     *
     * @param updateTime the value for product_params.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}