package com.lujun61.beans.entity;

public class UserLoginHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.ID
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.AREA
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.COUNTRY
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.USER_ID
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.IP
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.LOGIN_TIME
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.ID
     *
     * @return the value of user_login_history.ID
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.ID
     *
     * @param id the value for user_login_history.ID
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.AREA
     *
     * @return the value of user_login_history.AREA
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.AREA
     *
     * @param area the value for user_login_history.AREA
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.COUNTRY
     *
     * @return the value of user_login_history.COUNTRY
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.COUNTRY
     *
     * @param country the value for user_login_history.COUNTRY
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.USER_ID
     *
     * @return the value of user_login_history.USER_ID
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.USER_ID
     *
     * @param userId the value for user_login_history.USER_ID
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.IP
     *
     * @return the value of user_login_history.IP
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.IP
     *
     * @param ip the value for user_login_history.IP
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.LOGIN_TIME
     *
     * @return the value of user_login_history.LOGIN_TIME
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.LOGIN_TIME
     *
     * @param loginTime the value for user_login_history.LOGIN_TIME
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime == null ? null : loginTime.trim();
    }
}