package com.lujun61.beans.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;


@ApiModel(value = "User对象", description = "⽤户/买家信息")
public class User {

    @ApiModelProperty(dataType = "String",required = false)
    private String userId;

    @ApiModelProperty(dataType = "String",required = true, value = "⽤户注册账号")
    private String username;

    @ApiModelProperty(dataType = "String",required = true, value = "⽤户注册密码")
    private String password;

    private String nickname;

    private String realname;

    @ApiModelProperty(dataType = "String",required = true, value = "⽤户头像")
    private String userImg;

    private String userMobile;

    private String userEmail;

    private String userSex;

    private Date userBirth;

    private Date userRegtime;

    private Date userModtime;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nickname
     *
     * @return the value of users.nickname
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nickname
     *
     * @param nickname the value for users.nickname
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.realname
     *
     * @return the value of users.realname
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.realname
     *
     * @param realname the value for users.realname
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_img
     *
     * @return the value of users.user_img
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public String getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_img
     *
     * @param userImg the value for users.user_img
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg == null ? null : userImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_mobile
     *
     * @return the value of users.user_mobile
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_mobile
     *
     * @param userMobile the value for users.user_mobile
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_email
     *
     * @return the value of users.user_email
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_email
     *
     * @param userEmail the value for users.user_email
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_sex
     *
     * @return the value of users.user_sex
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_sex
     *
     * @param userSex the value for users.user_sex
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_birth
     *
     * @return the value of users.user_birth
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public Date getUserBirth() {
        return userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_birth
     *
     * @param userBirth the value for users.user_birth
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setUserBirth(Date userBirth) {
        this.userBirth = userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_regtime
     *
     * @return the value of users.user_regtime
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public Date getUserRegtime() {
        return userRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_regtime
     *
     * @param userRegtime the value for users.user_regtime
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setUserRegtime(Date userRegtime) {
        this.userRegtime = userRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_modtime
     *
     * @return the value of users.user_modtime
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public Date getUserModtime() {
        return userModtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_modtime
     *
     * @param userModtime the value for users.user_modtime
     *
     * @mbggenerated Mon Jul 18 22:55:48 CST 2022
     */
    public void setUserModtime(Date userModtime) {
        this.userModtime = userModtime;
    }
}