package com.lujun61.beans.entity;

import java.util.Date;

public class UserAddr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.addr_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String addrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.user_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.receiver_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.receiver_mobile
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.province
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.city
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.area
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.post_code
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.common_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Integer commonAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.addr_id
     *
     * @return the value of user_addr.addr_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.addr_id
     *
     * @param addrId the value for user_addr.addr_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setAddrId(String addrId) {
        this.addrId = addrId == null ? null : addrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.user_id
     *
     * @return the value of user_addr.user_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.user_id
     *
     * @param userId the value for user_addr.user_id
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.receiver_name
     *
     * @return the value of user_addr.receiver_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.receiver_name
     *
     * @param receiverName the value for user_addr.receiver_name
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.receiver_mobile
     *
     * @return the value of user_addr.receiver_mobile
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.receiver_mobile
     *
     * @param receiverMobile the value for user_addr.receiver_mobile
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.province
     *
     * @return the value of user_addr.province
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.province
     *
     * @param province the value for user_addr.province
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.city
     *
     * @return the value of user_addr.city
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.city
     *
     * @param city the value for user_addr.city
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.area
     *
     * @return the value of user_addr.area
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.area
     *
     * @param area the value for user_addr.area
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.addr
     *
     * @return the value of user_addr.addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.addr
     *
     * @param addr the value for user_addr.addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.post_code
     *
     * @return the value of user_addr.post_code
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.post_code
     *
     * @param postCode the value for user_addr.post_code
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.status
     *
     * @return the value of user_addr.status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.status
     *
     * @param status the value for user_addr.status
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.common_addr
     *
     * @return the value of user_addr.common_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Integer getCommonAddr() {
        return commonAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.common_addr
     *
     * @param commonAddr the value for user_addr.common_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCommonAddr(Integer commonAddr) {
        this.commonAddr = commonAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.create_time
     *
     * @return the value of user_addr.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.create_time
     *
     * @param createTime the value for user_addr.create_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.update_time
     *
     * @return the value of user_addr.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.update_time
     *
     * @param updateTime the value for user_addr.update_time
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}