server:
  port: 9203

spring:
  application:
    name: stock-update

  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.lujun61.beans.entity

eureka:
  client:
    service-url:
      defaultZone: http://rainlu:123456@localhost:8761/eureka# \u5E94\u7528\u540D\u79F0


