package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.Category;
import com.lujun61.beans.entity.MultiCategory;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CategoryMapper {

    /**
     * @return List<MultiCategory>
     * @description 连接查询，一次性查询所有的类别信息
     * @author Jun Lu
     * @date 2022-07-30 12:55:42
     */
    List<MultiCategory> selectAllCategory();

    /**
     * @param parentId 应该为所有层级的根层级。这里应是层级1
     * @return List<MultiCategory>
     * @description 子查询，递归查询所有的类别信息。
     * @author Jun Lu
     * @date 2022-07-30 12:55:42
     */
    List<MultiCategory> childrenSelectAllCategory(int parentId);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    Category selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(Category record);
}