package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.IndexImg;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface IndexImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(IndexImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(IndexImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    IndexImg selectByPrimaryKey(String imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(IndexImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(IndexImg record);

    /**
     * @return java.util.List<com.lujun61.beans.entity.IndexImg>
     * @description 查询首页轮播图
     * @author Jun Lu
     * @date 2022-07-29 16:34:21
     */
    List<IndexImg> selectIndexImgList();
}