package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.Orders;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

@Repository
public interface OrdersMapper {

    /**
     * @param deadlineTime 超时时刻
     * @return java.util.List<com.lujun61.beans.entity.Orders>
     * @description 查询超过指定时间（小于deadlineTime）并且订单状态为“未支付（1）”的订单
     * @author Jun Lu
     * @date 2022-08-11 20:20:47
     */
    List<Orders> selectTimeOutOrders(Date deadlineTime);

    /**
     * @param orderId 订单id
     * @param status 订单状态
     * @description 修改订单对应的状态
     * @author Jun Lu
     * @date 2022-08-10 22:18:44
     */
    int updateOrderStatusByOrderId(@Param("orderId") String orderId, @Param("status") String status);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    Orders selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(Orders record);
}