package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.DetailOrderItem;
import com.lujun61.beans.entity.OrderItem;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderItemMapper {

    /**
     * @return java.util.List<com.lujun61.beans.entity.DetailOrderItem> 封装有原OrderItem扩展的数据
     * @description 查询当前用户的订单详情；如果有订单状态，则条件上捎带着订单状态。
     * @author Jun Lu
     * @date 2022-09-15 18:01:27
     */
    List<DetailOrderItem> selectDetailOrderItems(@Param("userId") String userId, @Param("status") String status,
                                                 @Param("start") Integer start,
                                                 @Param("pageSize") Integer pageSize);

    /**
     * @return int 订单明细的数量
     * @description 查询当前用户的不同订单状态下的订单明细总数
     * @author Jun Lu
     * @date 2022-09-15 18:02:49
     */
    int selectDetailOrderItemsCount(@Param("userId") String userId, @Param("status") String status);

    /**
     * @param orderId 订单id
     * @return java.util.List<com.lujun61.beans.entity.OrderItem>
     * @description 根据订单id查询订单快照信息
     * @author Jun Lu
     * @date 2022-08-11 21:04:26
     */
    List<OrderItem> selectOrderItemsByOrderId(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    OrderItem selectByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(OrderItem record);
}