package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.ProductComments;

public interface ProductCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(ProductComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(ProductComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    ProductComments selectByPrimaryKey(String commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(ProductComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(ProductComments record);
}