package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.ProductParams;
import org.springframework.stereotype.Repository;

@Repository
public interface ProductParamsMapper {

    /**
     * @param productId 关联的商品id
     * @return com.lujun61.beans.entity.ProductParams
     * @description 根据商品id查询商品的参数信息
     * @author Jun Lu
     * @date 2022-08-02 13:38:32
     */
    ProductParams selectProductParamsByProductId(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    ProductParams selectByPrimaryKey(String paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(ProductParams record);
}