package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.Product;
import com.lujun61.beans.entity.ProductDetail;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProductMapper {

    /**
     * @param keyword 商品名（部分）
     * @return java.util.List<com.lujun61.beans.entity.ProductDetail>
     * @description 根据keyword模糊查询详细商品信息
     * @author Jun Lu
     * @date 2022-08-12 19:24:13
     */
    List<ProductDetail> vagueSelectDetailProduct(@Param("keyword") String keyword,
                                                 @Param("start") Integer start,
                                                 @Param("limit") Integer pageSize);

    /**
     * @param keyword 商品名（部分）
     * @description 根据keyword模糊查询出的商品总数    【分页需要】
     * @author Jun Lu
     * @date 2022-08-12 19:28:12
     */
    int vagueSelectCountDetailProduct(String keyword);

    /**
     * @param categoryId 类别id
     * @param start 起始页码
     * @param pageSize 每页数据显示长度
     * @return java.util.List<com.lujun61.beans.entity.ProductDetail>
     * @description 根据类别id查询此类别下所有的商品信息。（另：子查询商品套餐）
     * @author Jun Lu
     * @date 2022-08-12 09:21:49
     */
    List<ProductDetail> selectDetailProductByCategoryId(@Param("cid") Integer categoryId,
                                                        @Param("start") Integer start,
                                                        @Param("limit") Integer pageSize);

    /**
     * @param categoryId 类别id
     * @return int 当前类别下的商品总数
     * @description 根据类别id查询当前类别下的商品总数    【分页需要】
     * @author Jun Lu
     * @date 2022-08-12 10:30:411
     */
    int selectCountDetailProductByCategoryId(Integer categoryId);

    /**
     * @param productId 主键：商品ID
     * @param status 商品状态
     * @return com.lujun61.beans.entity.Product
     * @description 根据商品ID以及商品状态查询商品
     * @author Jun Lu
     * @date 2022-08-01 19:16:23
     */
    Product selectProductByPrimaryKeyAndStatus(@Param("productId") String productId, @Param("status") int status);

    /**
     * @param categoryId 某个一级类别的类别id
     * @return java.util.List<com.lujun61.beans.entity.ProductDetail>
     * @description 查询属于一级类别的商品销量为前6的商品信息（被作为子查询使用）
     * @author Jun Lu
     * @date 2022-07-31 16:09:52
     */
    List<ProductDetail> selectFirstLevelTopSixRecommendProducts(int categoryId);

    /**
     * @return java.util.List<com.lujun61.beans.entity.ProductDetail>
     * @description 查询首页推荐商品信息（“算法”思路：无视分类，查询所有商品中销量最高的商品信息Top3）
     * @author Jun Lu
     * @date 2022-07-30 21:46:06
     */
    List<ProductDetail> selectRecommendProducts();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    Product selectByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(Product record);
}