package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.DetailProductComments;
import com.lujun61.beans.entity.ProductComments;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProductCommentsMapper {


    /**
     * @param productId 商品id
     * @return int
     * @description 根据商品id查询商品评论总数
     * @author Jun Lu
     * @date 2022-08-03 08:33:06
     */
    int selectProductCommentCountByProductId(String productId);

    /**
     * @param productId 商品id
     * @description 查询商品对应的好评数
     * @author Jun Lu
     * @date 2022-08-03 11:26:21
     */
    int selectCountForNiceCommentByProductId(String productId);

    /**
     * @param productId 商品id
     * @description 查询商品对应的中评数
     * @author Jun Lu
     * @date 2022-08-03 11:26:21
     */
    int selectCountForMidCommentByProductId(String productId);

    /**
     * @param productId 关联的商品id
     * @param start 分页起始条数：由后端计算得出
     * @param pageSize 每页显示条数
     * @return java.util.List<com.lujun61.beans.entity.DetailProductComments>
     * @description 查询对应商品的评论信息，并分页显示
     * @author Jun Lu
     * @date 2022-08-03 08:43:24
     */
    List<DetailProductComments> pageSelectDetailProductCommentsByProductId(
            @Param("productId") String productId,
            @Param("start") int start,
            @Param("pageSize") int pageSize
    );

    /**
     * @param productId 关联的商品id
     * @return java.util.List<com.lujun61.beans.entity.DetailProductComments>
     * @description 查询对应商品的评论信息
     * @author Jun Lu
     * @date 2022-08-02 22:34:43
     */
    List<DetailProductComments> selectDetailProductCommentsByProductId(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(ProductComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(ProductComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    ProductComments selectByPrimaryKey(String commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(ProductComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(ProductComments record);
}