package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.ProductImg;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProductImgMapper {

    /**
     * @param itemId 商品id
     * @return java.util.List<com.lujun61.beans.entity.ProductImg>
     * @description 根据商品id，查询所关联的图片信息
     * @author Jun Lu
     * @date 2022-08-01 20:09:45
     */
    List<ProductImg> selectProductImgsByProductId(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(ProductImg record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_img
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(ProductImg record);
}