package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.ProductParams;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProductParamsMapper {

    /**
     * @param keyword 商品名（部分）
     * @return java.util.List<java.lang.String>
     * @description 查询根据keyword模糊查询出来的商品品牌
     * @author Jun Lu
     * @date 2022-08-12 19:46:00
     */
    List<String> vagueSelectBrand(String keyword);

    /**
     * @param categoryId 商品类别
     * @return java.util.List<java.lang.String>
     * @description 查询某商品类别下所有的商品品牌
     * @author Jun Lu
     * @date 2022-08-12 12:04:57
     */
    List<String> selectBrandByCategoryId(Integer categoryId);

    /**
     * @param productId 关联的商品id
     * @return com.lujun61.beans.entity.ProductParams
     * @description 根据商品id查询商品的参数信息
     * @author Jun Lu
     * @date 2022-08-02 13:38:32
     */
    ProductParams selectProductParamsByProductId(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    ProductParams selectByPrimaryKey(String paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(ProductParams record);
}