package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.ProductParams;

public interface ProductParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    ProductParams selectByPrimaryKey(String paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(ProductParams record);
}