package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.DetailShoppingCart;
import com.lujun61.beans.entity.ShoppingCart;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ShoppingCartMapper {

    /**
     * @param cartIds 多个购物车商品id
     * @description 根据多个购物车商品id进行批量删除操作
     * @author Jun Lu
     * @date 2022-09-15 20:25:29
     */
    int batchDelByCartIds(List<String> cartIds);

    /**
     * @param cartId 购物车商品id
     * @description 根据单个购物车商品id进行删除操作
     * @author Jun Lu
     * @date 2022-09-15 20:23:37
     */
    int delByCartId(@Param("cartId") String cartId);

    /**
     * @param cartIds 用户提交的所选定的需要结算的购物车商品信息的id
     * @return java.util.List<com.lujun61.beans.entity.ShoppingCart>
     * @description 根据用户所提交的需要结算的购物车商品信息的id查询购物车商品信息
     * @author Jun Lu
     * @date 2022-08-07 11:10:51
     */
    List<DetailShoppingCart> selectShopcartByCartIds(List<String> cartIds);

    /**
     * @param cartId 购物车主键
     * @param cartNum 商品个数的目标修改值
     * @description 修改指定购物车商品信息的商品个数
     * @author Jun Lu
     * @date 2022-08-06 11:34:52
     */
    int updateCartnumByCartid(@Param("cartId") String cartId,
                                     @Param("cartNum") String cartNum);

    /**
     * @param userId 用户id
     * @return java.util.List<com.lujun61.beans.entity.DetailShoppingCart>
     * @description 根据用户id查询当前用户的购物车列表
     * @author Jun Lu
     * @date 2022-08-05 21:15:53
     */
    List<DetailShoppingCart> selectShoppingCartByUserId(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbggenerated Thu Aug 04 20:56:05 CST 2022
     */
    int deleteByPrimaryKey(String cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbggenerated Thu Aug 04 20:56:05 CST 2022
     */
    int insert(ShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbggenerated Thu Aug 04 20:56:05 CST 2022
     */
    int insertSelective(ShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbggenerated Thu Aug 04 20:56:05 CST 2022
     */
    ShoppingCart selectByPrimaryKey(String cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbggenerated Thu Aug 04 20:56:05 CST 2022
     */
    int updateByPrimaryKeySelective(ShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbggenerated Thu Aug 04 20:56:05 CST 2022
     */
    int updateByPrimaryKey(ShoppingCart record);
}