package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.UserLoginHistory;

public interface UserLoginHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(UserLoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(UserLoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    UserLoginHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(UserLoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_history
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(UserLoginHistory record);
}