package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.UserAddr;

public interface UserAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(UserAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(UserAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    UserAddr selectByPrimaryKey(String addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(UserAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(UserAddr record);
}