package com.lujun61.fmmall.dao;

import com.lujun61.beans.entity.UserAddr;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserAddrMapper {

    /**
     * @param userId 用户ID
     * @return java.util.List<com.lujun61.beans.entity.UserAddr>
     * @description 根据用户id查询该用户所登记的住址信息
     * @author Jun Lu
     * @date 2022-08-07 11:07:34
     */
    List<UserAddr> selectAddrsByUid(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int deleteByPrimaryKey(String addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insert(UserAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int insertSelective(UserAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    UserAddr selectByPrimaryKey(String addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKeySelective(UserAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addr
     *
     * @mbggenerated Fri Jul 29 10:45:02 CST 2022
     */
    int updateByPrimaryKey(UserAddr record);
}