server:
  port: 8761

spring:
  application:
    name: service-eureka
  security:
    user:
      name: rainlu
      password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://rainlu:123456@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false