server:
  port: 9201

spring:
  application:
    name: order-add

  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.lujun61.beans.entity

eureka:
  client:
    service-url:
      defaultZone: http://rainlu:123456@localhost:8761/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ConnectTimeout: 1000
  MaxAutoRetries: 2
  ReadTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000