spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
  redis:
    host: 192.168.153.130
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.lujun61.beans.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印日志

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
